version: "3.9"

services:
  web:
    build: .
    container_name: myapp-web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # If your app reads envs, you can use these
      # PHP will see these as $_ENV/$_SERVER variables
      - APP_ENV=local
      - DB_HOST=mysql
      - DB_NAME=myapp
      - DB_USER=myuser
      - DB_PASS=mypassword
    networks:
      - myapp-net

  mysql:
    image: mysql:8.0
    container_name: myapp-mysql
    restart: unless-stopped
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_DATABASE: myapp
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - myapp-net

volumes:
  mysql_data:

networks:
  myapp-net:
